"""Add pending_email

Revision ID: 1007d3ddb50b
Revises: a7ee424590d2
Create Date: 2025-12-04 03:12:08.760724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1007d3ddb50b'
down_revision = 'a7ee424590d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['pending_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
