"""Initial schema with user_agent

Revision ID: 404b5b5e823e
Revises: 
Create Date: 2025-11-09 13:46:37.560753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404b5b5e823e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_attempt_log', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ip_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_attempt_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
