"""Add ON DELETE CASCADE to cart_items.shop_id

Revision ID: 6286fbf51c77
Revises: cf2e69afd302
Create Date: 2025-11-27 00:12:23.264906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6286fbf51c77'
down_revision = 'cf2e69afd302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cart_items_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_items_product_id_fkey'), 'shop', ['product_id'], ['id'])

    # ### end Alembic commands ###
