"""Добавлено поле is_blocked в ip_attempt_log

Revision ID: 772f8a796603
Revises: 506e80d443b3
Create Date: 2025-11-11 18:08:33.963204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772f8a796603'
down_revision = '506e80d443b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_attempt_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_attempt_log', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
