"""Убрать FK из user_tokens.user_id

Revision ID: 7cb4661cd267
Revises: 602f5c2e5db7
Create Date: 2025-11-11 15:02:23.683264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb4661cd267'
down_revision = '602f5c2e5db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_tokens_user_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('user_tokens_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
