"""Make order_items.product_id nullable for SET NULL

Revision ID: fb8df1fca16f
Revises: 6286fbf51c77
Create Date: 2025-11-27 01:04:30.521879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8df1fca16f'
down_revision = '6286fbf51c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('dialogs_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop', ['product_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('dialogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dialogs_product_id_fkey'), 'shop', ['product_id'], ['id'])

    # ### end Alembic commands ###
